-- config.lua

Config = {}

Config.Items = {
    general = {
        { itemLabel = "Bread Roll", itemName = "consumable_bread_roll", price = 5 },
        { itemLabel = "Cooked Meat", itemName = "consumable_meat_cooked", price = 15 },
        { itemLabel = "Whisky", itemName = "drink_whisky", price = 10 },
        { itemLabel = "Bandage", itemName = "medical_bandage", price = 7 },
        { itemLabel = "Hammer", itemName = "tool_hammer", price = 12 },
    },
    weapon = {
        { itemLabel = "Cattleman Revolver", itemName = "WEAPON_REVOLVER_CATTLEMAN", price = 13, ammoPrice = 10 },
        { itemLabel = "Double-Action Revolver", itemName = "WEAPON_REVOLVER_DOUBLEACTION", price = 15, ammoPrice = 10 },
        { itemLabel = "Schofield Revolver", itemName = "WEAPON_REVOLVER_SCHOFIELD", price = 17, ammoPrice = 10 },
        { itemLabel = "LeMat Revolver", itemName = "WEAPON_REVOLVER_LEMAT", price = 25, ammoPrice = 10 },
        { itemLabel = "Volcanic Pistol", itemName = "WEAPON_PISTOL_VOLCANIC", price = 25, ammoPrice = 10 },
        { itemLabel = "Semi-Automatic Pistol", itemName = "WEAPON_PISTOL_SEMIAUTO", price = 40, ammoPrice = 10 },
        { itemLabel = "Mauser Pistol", itemName = "WEAPON_PISTOL_MAUSER", price = 45, ammoPrice = 10 },
        { itemLabel = "Carbine Repeater", itemName = "WEAPON_REPEATER_CARBINE", price = 60, ammoPrice = 10 },
        { itemLabel = "Lancaster Repeater", itemName = "WEAPON_REPEATER_WINCHESTER", price = 63, ammoPrice = 10 },
        { itemLabel = "Carbine Repeater", itemName = "WEAPON_REPEATER_EVANS", price = 63, ammoPrice = 10 },
        { itemLabel = "Litchfield Repeater", itemName = "WEAPON_REPEATER_HENRY", price = 65, ammoPrice = 10 },
        { itemLabel = "Varmint Rifle", itemName = "WEAPON_RIFLE_VARMINT", price = 35, ammoPrice = 10 },
        { itemLabel = "Springfield Rifle", itemName = "WEAPON_RIFLE_SPRINGFIELD", price = 55, ammoPrice = 20 },
        { itemLabel = "Bolt-Action Rifle", itemName = "WEAPON_RIFLE_BOLTACTION", price = 65, ammoPrice = 20 },
        { itemLabel = "Rolling-Block Rifle", itemName = "WEAPON_SNIPERRIFLE_ROLLINGBLOCK", price = 75, ammoPrice = 30 },
        { itemLabel = "Carcano Rifle", itemName = "WEAPON_SNIPERRIFLE_CARCANO", price = 70, ammoPrice = 20 },
        { itemLabel = "Sawed-Off Shotgun", itemName = "WEAPON_SHOTGUN_SAWEDOFF", price = 25, ammoPrice = 10 },
        { itemLabel = "Double-Barrel Shotgun", itemName = "WEAPON_SHOTGUN_DOUBLEBARREL", price = 33, ammoPrice = 10 },
        { itemLabel = "Pump-Action Shotgun", itemName = "WEAPON_SHOTGUN_PUMP", price = 40, ammoPrice = 10 },
        { itemLabel = "Repeating Shotgun", itemName = "WEAPON_SHOTGUN_REPEATING", price = 43, ammoPrice = 10 },
        { itemLabel = "Semi-Automatic Shotgun", itemName = "WEAPON_SHOTGUN_SEMIAUTO", price = 45, ammoPrice = 10 },
        { itemLabel = "Hunting Bow", itemName = "WEAPON_BOW", price = 20, ammoPrice = 5 },
        { itemLabel = "Lasso", itemName = "WEAPON_LASSO", price = 5, ammoPrice = 0 },
        { itemLabel = "Antique Sword", itemName = "WEAPON_MELEE_BROKEN_SWORD", price = 20, ammoPrice = 0 },
        { itemLabel = "Lantern", itemName = "WEAPON_MELEE_LANTERN", price = 10, ammoPrice = 0 },
        { itemLabel = "Hatchet", itemName = "WEAPON_MELEE_HATCHET", price = 15, ammoPrice = 0 },
        { itemLabel = "Hunting Knife", itemName = "WEAPON_MELEE_KNIFE", price = 10, ammoPrice = 0 },
        { itemLabel = "Throwing Knives", itemName = "WEAPON_THROWN_THROWING_KNIVES", price = 10, ammoPrice = 0 },
        { itemLabel = "Machete", itemName = "WEAPON_MELEE_MACHETE", price = 20, ammoPrice = 0 },
        { itemLabel = "Tomahawk", itemName = "WEAPON_THROWN_TOMAHAWK", price = 15, ammoPrice = 0 },
        { itemLabel = "Dynamite Sticks", itemName = "WEAPON_THROWN_DYNAMITE", price = 50, ammoPrice = 0 },
        { itemLabel = "Fire Bottles", itemName = "WEAPON_THROWN_MOLOTOV", price = 30, ammoPrice = 0 },
        { itemLabel = "Revolver Ammo", itemName = "revolver_ammo", price = 10, ammoPrice = 10 },
        { itemLabel = "Pistol Ammo", itemName = "pistol_ammo", price = 10, ammoPrice = 10 },
        { itemLabel = "Varmint Ammo", itemName = "22_ammo", price = 10, ammoPrice = 10 },
        { itemLabel = "Rifle Ammo", itemName = "rifle_ammo", price = 10, ammoPrice = 15 },
        { itemLabel = "Shotgun Ammo", itemName = "shotgun_ammo", price = 10, ammoPrice = 10 },
        { itemLabel = "Repeater Ammo", itemName = "repeator_ammo", price = 10, ammoPrice = 10 },
        { itemLabel = "Sniper Ammo", itemName = "snipe_ammo", price = 10, ammoPrice = 30 },
        { itemLabel = "Arrows", itemName = "arrows", price = 10, ammoPrice = 10 },
    },
    fishing = {
        { itemLabel = "Fishing Rod", itemName = "tool_fishingrod", price = 30 },
        { itemLabel = "Worm Bait", itemName = "bait_worm", price = 3 },
        { itemLabel = "Fish Meat", itemName = "consumable_fish", price = 5 },
    }
}

Config.Stores = {
    Valentine = {
        storetype = "general",
        isDeactivated = false,
        useRandomLocation = false,
        possibleLocations = {
            OpenMenu = { vector3(-324.628, 803.9818, 116.88) },
            Npcs = { vector4(-324.628, 803.9818, 116.88, -81.17) },
        },
        Blip = { Allowed = true, Name = "Valentine Store", sprite = 1475879922, Pos = vector3(-324.628, 803.9818, 116.88) },
        Npc = { Allowed = true, Pos = vector4(-324.628, 803.9818, 116.88, -81.17), distanceRemoveNpc = 20.0, Model = "U_M_M_NbxGeneralStoreOwner_01" },
        storeName = "Valentine General Store",
        PromptName = "General Store",
        AllowedJobs = {},
        JobGrade = 0,
        StoreHoursAllowed = true,
        RandomPrices = true,
        StoreOpen = 7,
        StoreClose = 21,
        DynamicStore = true,
        distanceOpenStore = 3.0,
    },
    Rhodes = {
        storetype = "general",
        isDeactivated = false,
        useRandomLocation = false,
        possibleLocations = {
            OpenMenu = { vector3(1330.227, -1293.41, 76.021) },
            Npcs = { vector4(1330.227, -1293.41, 76.021, 68.88) },
        },
        Blip = { Allowed = true, Name = "Rhodes Store", sprite = 1475879922, Pos = vector3(1330.227, -1293.41, 76.021) },
        Npc = { Allowed = true, Pos = vector4(1330.227, -1293.41, 76.021, 68.88), distanceRemoveNpc = 20.0, Model = "S_M_M_UNIBUTCHERS_01" },
        storeName = "Rhodes General Store",
        PromptName = "General Store",
        AllowedJobs = {},
        JobGrade = 0,
        StoreHoursAllowed = true,
        RandomPrices = true,
        StoreOpen = 7,
        StoreClose = 21,
        DynamicStore = true,
        distanceOpenStore = 3.0,
    },
    WeaponStore = {
        storetype = "weapon",
        isDeactivated = false,
        useRandomLocation = false,
        possibleLocations = {
            OpenMenu = { vector3(2947.246, 1319.698, 44.88) },
            Npcs = { vector4(2947.246, 1319.698, 44.88, 72.38) },
        },
        Blip = { Allowed = true, Name = "Weapon Store", sprite = 1475879922, Pos = vector3(2947.246, 1319.698, 44.88) },
        Npc = { Allowed = true, Pos = vector4(2947.246, 1319.698, 44.88, 72.38), distanceRemoveNpc = 20.0, Model = "U_M_M_NbxGeneralStoreOwner_01" },
        storeName = "Weapon Store",
        PromptName = "Weapon Store",
        AllowedJobs = {},
        JobGrade = 0,
        StoreHoursAllowed = true,
        RandomPrices = true,
        StoreOpen = 7,
        StoreClose = 21,
        DynamicStore = true,
        distanceOpenStore = 3.0,
    }
}

return Config
